library(VennDiagram)

# OA Venn Diagram
VennDiagram::venn.diagram(x = list(SEstim_outlier$loc_name, BScan_outlier$loc_name, PCAdapt_outlier$loc_name),
             category.names = c("SelEstim" , "Bayescan" , "pcadapt"),
             filename = 'data/final/venn-OA.png',
             output = TRUE,
             imagetype="png" ,
             height = 480 , 
             width = 480 , 
             resolution = 300,
             compression = "lzw",
             lwd = 2,
             lty = 'blank',
             fill = c('blue', 'purple', 'green'),
             cex = 1,
             fontface = "bold",
             fontfamily = "sans",
             cat.cex = 0.6,
             cat.fontface = "bold",
             cat.default.pos = "outer",
             cat.pos = c(-27, 27, 135),
             cat.dist = c(0.055, 0.055, 0.085),
             cat.fontfamily = "sans",
             rotation = 1
)

# OA Venn Diagram
VennDiagram::venn.diagram(x = list(unique(unlist(lfmm_list)), sig_sambada$Marker),
                          category.names = c("LFMM" , "SamBada"),
                          filename = 'data/final/venn-EAA.png',
                          output = TRUE,
                          imagetype="png" ,
                          height = 480 , 
                          width = 480 , 
                          resolution = 300,
                          compression = "lzw",
                          lwd = 2,
                          lty = 'blank',
                          fill = c('yellow', 'red'),
                          cex = 1,
                          fontface = "bold",
                          fontfamily = "sans",
                          cat.cex = 0.6,
                          cat.fontface = "bold",
                          cat.default.pos = "outer",
                          cat.pos = c(-90, 90),
                          cat.dist = c(0.055, -0.055),
                          cat.fontfamily = "sans",
                          rotation = 1,
)
