title = "sambada parameters"

[debug]
shape = "SHAPEFILE Yes"
header = "HEADERS Yes"
delim = "WORDDELIM"
n_env = "NUMVARENV "
n_mark = "NUMMARK "
n_ind = "NUMINDIV "
ind_id = "IDINDIV "
spatial = "SPATIAL longitude latitude CARTESIAN BISQUARE 10"
autocor = "AUTOCORR BOTH BOTH 100"
pop = "POPULATIONVAR LAST"
dim = "DIMMAX 2"
save = "SAVETYPE END ALL"
alpha = 0.01 # Adjust to 0.05 to decrease stringency

[release]
shape = "SHAPEFILE Yes"
header = "HEADERS Yes"
delim = "WORDDELIM"
n_env = "NUMVARENV "
n_mark = "NUMMARK "
n_ind = "NUMINDIV "
ind_id = "IDINDIV "
spatial = "SPATIAL longitude latitude CARTESIAN BISQUARE 10"
autocor = "AUTOCORR BOTH BOTH 100"
pop = "POPULATIONVAR LAST"
dim = "DIMMAX 2"
save = "SAVETYPE END ALL"
alpha = 0.01 # Adjust to 0.05 to decrease stringency