title = "data processing parameters"

[debug]
species_eng_names = ["western spadefoot toad"]
species_sci_names = ["Pelobates cultripes"]
species_atlas_names = ["pelcul"] ## note that we use different atlas data for Pelobates for debugging since otherwise raptr cannot be run on my computer with 8GB RAM, which makes debugging dificult
species_snp_metadata_path = [
  "data/raw/Report-DPelo19-4013/2019-01-10_lab_Pelobate-DArT-Submission.xlsx"
]
species_snp_raw_path = [
  "data/raw/Report-DPelo19-4013/Report_DPelo19-4013_SNP_2.csv"
]

[release]
species_eng_names = ["western spadefoot toad"]
species_sci_names = ["Pelobates cultripes"]
species_atlas_names = ["pelcul"]
species_snp_metadata_path = [
  "data/raw/Report-DPelo19-4013/2019-01-10_lab_Pelobate-DArT-Submission.xlsx"
]
species_snp_raw_path = [
  "data/raw/Report-DPelo19-4013/Report_DPelo19-4013_SNP_2.csv"
]
